# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
total = 0
n_minus_1 = None
n_minus_2 = None
term = None
i = 1
while term <= 4000000:
    if i == 1:
        term = i
    elif i == 2:
        n_minus_1 = term
        term = i
    else:
        n_minus_2 = n_minus_1
        n_minus_1 = term
        term = n_minus_1 + n_minus_2
    if term % 2 == 0:
        total += term
    i += 1

print total
# >>> 4613732
